#!/bin/bash
#compile64.sh

# Script de compilation pour programme en assembleur NASM utilisant 'main'

file_base=$(basename $1 .asm)
nasm -felf64 -o ${file_base}.o ${file_base}.asm
gcc -m64 -no-pie -o ${file_base}_executable ${file_base}.o

if [ $? -eq 0 ]; then
    echo "Compilation réussie. Exécutable généré : ${file_base}_executable"
    rm ${file_base}.o
else
    echo "Erreur lors de la compilation."
fi